version: '3.8'

services:
  web:
    build:
      context: ./WebApp
    ports:
      - "8080:80"
    depends_on:
      - api

  api:
    build:
      context: ./PythonApp
    ports:
      - "5000:5000"
